#!/usr/bin/env python3
"""Render THIRD-PARTY-LICENSES.md from `cargo about generate --format json`.

cargo-about resolves and elects the licenses (and fails on anything outside the
allowlist in about.toml); this renders its JSON, which its handlebars templates
cannot do: the per-crate copyright lines are buried in license *text*, so they
have to be pulled out with a regex and hoisted into the crate table. Each
license text is then reproduced once, with its copyright line pointing back at
that table instead of naming whichever crate happened to be listed first.
"""
import json, pathlib, re, subprocess, sys, textwrap

OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "THIRD-PARTY-LICENSES.md"

# A real copyright line starts the line and carries a year. That skips the
# boilerplate ("The above copyright notice...", "SHALL THE COPYRIGHT HOLDERS")
# and CC0's prose, which mention copyright mid-sentence.
COPYRIGHT = re.compile(r"^[ \t]*Copyright\b.*?\d{4}.*$", re.M | re.I)
PLACEHOLDER = "Copyright (c) the holders listed against each crate above"


def holders(text, authors, name):
    """Copyright line(s) for one crate: its license file, else Cargo.toml, else the crate."""
    found = []
    for line in COPYRIGHT.findall(text):
        line = re.sub(r"^[ \t]*Copyright\s*(\(c\)|\(C\)|©)?\s*", "", line).strip(" .,")
        line = re.sub(r"\s*All rights reserved\.?$", "", line, flags=re.I)
        if line and line not in found:
            found.append(line)
    if found:
        return "; ".join(found)
    if authors:
        # Manifest authors carry no year; the crate's own files are the record.
        return "; ".join(re.sub(r"\s*<[^>]*>", "", a).strip() for a in authors)
    return f"The {name} authors"


def main():
    try:
        data = json.loads(subprocess.check_output(
            ["cargo", "about", "generate", "--format", "json"], cwd=OUTPUT.parent))
    except FileNotFoundError:
        sys.exit("cargo-about is not installed: "
                 "cargo install cargo-about --locked --features cli")

    crates = {}   # (name, version) -> {"copyright": str, "licenses": [id]}
    for entry in data["licenses"]:
        for used in entry["used_by"]:
            pkg = used["crate"]
            key = (pkg["name"], pkg["version"])
            row = crates.setdefault(key, {"copyright": "", "licenses": []})
            row["licenses"].append(entry["id"])
            row["copyright"] = row["copyright"] or holders(
                entry["text"], pkg.get("authors"), pkg["name"])

    missing = {(c["package"]["name"], c["package"]["version"]) for c in data["crates"]} - set(crates)
    if missing:
        sys.exit(f"no license text resolved for: {sorted(missing)}")

    out = [textwrap.dedent("""\
        # Third-party licenses

        `tauri-greeter` is distributed as a statically linked binary. It compiles in the crates
        below, all under permissive, GPLv3-compatible terms. tauri-greeter's own license is in
        [LICENSE](LICENSE).

        Where a crate offers a choice of licenses, the one named here is the one tauri-greeter
        elects, so those are the only terms that apply. Only crates that reach a Linux
        build are listed; dev-only and other-platform dependencies are not.

        Each crate's copyright holders are named in the table, so the license texts at
        the end are reproduced once each rather than once per copyright holder.

        Generated by `make third-party` — do not edit by hand.

        ## Licenses used
        """)]
    for over in data["overview"]:
        plural = "crate" if over["count"] == 1 else "crates"
        out.append(f"- **{over['name']}** (`{over['id']}`) — {over['count']} {plural}")

    out.append("\n## Crates\n")
    out.append("| Crate | Version | Copyright | License |")
    out.append("| --- | --- | --- | --- |")
    for (name, version), row in sorted(crates.items()):
        ids = " AND ".join(dict.fromkeys(row["licenses"]))
        copyright = row["copyright"].replace("|", r"\|").replace("<", r"\<")
        out.append(f"| {name} | {version} | {copyright} | `{ids}` |")

    out.append("\n## License texts\n")
    out.append("One copy of each license above, as those licenses require.\n")
    for entry in data["licenses"]:
        if not entry.get("first_of_kind"):
            continue
        # Collapse the original holder's lines into one pointer at the table.
        text = COPYRIGHT.sub(PLACEHOLDER, entry["text"])
        text = re.sub(rf"(?:{re.escape(PLACEHOLDER)}\n)+", PLACEHOLDER + "\n", text)
        out.append(f"### {entry['name']}\n\n```\n{text.strip()}\n```\n")

    OUTPUT.write_text("\n".join(out) + "\n")
    print(f"{OUTPUT.name}: {len(crates)} crates, {len(data['overview'])} licenses")


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        assert holders("Copyright (c) 2014 Alex Crichton\n\nPermission...", None, "x") == "2014 Alex Crichton"
        assert holders("Copyright (c) 2006 A\nCopyright (c) 2016 B", None, "x") == "2006 A; 2016 B"
        assert holders("The above copyright notice shall be included", ["Jo <j@e.com>"], "x") == "Jo"
        assert holders("no notice here", None, "kittens") == "The kittens authors"
        print("ok")
    else:
        main()
